apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa1
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          directories:
          - path: web-app
          - path: test-app
          repoURL: https://github.com/Akshaya-Parthi/helm-charts.git
          revision: HEAD
      - list:
          elements:
          - appSuffix: qa1
            namespace: qa1
            project: prod
            valuesFile: values-qa1.yaml
  template:
    metadata:
      name: '{{path.basename}}-{{appSuffix}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{path.basename}}={{path.basename}}"
        argocd-image-updater.argoproj.io/{{path.basename}}.update-strategy: latest
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false
        syncOptions:
        - CreateNamespace=false
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      project: '{{project}}'
      source:
        helm:
          releaseName: '{{path.basename}}'
          valueFiles:
          - '{{valuesFile}}'
          version: v3
        path: '{{path.basename}}'
        repoURL: https://github.com/Akshaya-Parthi/helm-charts.git
        targetRevision: main
