helm:
  parameters:
  - name: image.name
    value: 739275447850.dkr.ecr.ap-south-1.amazonaws.com/web-app
    forcestring: true
  - name: image.tag
    value: 161120240646c17c4666
    forcestring: true
