helm:
  parameters:
  - name: image.name
    value: 739275447850.dkr.ecr.ap-south-1.amazonaws.com/test-app
    forcestring: true
  - name: image.tag
    value: 171120240646a18b3999
    forcestring: true
